name: mkdocs-build-deploy-1.x
run-name: MkDocs build from {{ github.ref_name }} branch and deploy to gh-pages
on:
  push:
    branches:
      - "1.*"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Cache key for weekly updates
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-material-
      - run: pip install mkdocs-material mike
      - name: Deploy branch
        run: mike deploy --push ${GITHUB_REF_NAME}
