name: mkdocs-build-deploy
run-name: MkDocs build from {{ github.ref_name }} branch and deploy to gh-pages
on: push
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Fetch gh-pages
        run: git fetch --depth 1 origin gh-pages:gh-pages
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Cache for weekly updates
        uses: actions/cache@v4
        with:
          key: mkdocs-material-$(date --utc '+%Y-%V')
          path: ~/.cache/pip
          restore-keys: mkdocs-material-
      - run: pip install mkdocs-material mike
      - name: Deploy arbitrary branch
        if: ${{github.ref_name != 'master' }}
        run: mike deploy --push ${GITHUB_REF_NAME}
      - name: Deploy master
        if: ${{github.ref_name == 'master' }}
        run: |
          mike deploy --push --update-aliases $(cat VERSION) latest
          mike set-default --push latest
